export const KIZAMU_TERMINAL_SCRIPT = [
  { text: "$ pip install kizamu-manga\n", speed: 52, variance: 14 },
  { pause: 620 },
  { text: "Successfully installed kizamu-manga\n", speed: 28, variance: 8 },
  { text: "$ playwright install\n", speed: 48, variance: 12 },
  { pause: 520 },
  { text: "Playwright browsers installed\n", speed: 28, variance: 8 },
  { pause: 900 },
  { clear: true, pause: 180 },
  { text: "$ kizamumanga --help\n\n", speed: 50, variance: 12 },
  { text: "Usage: kizamumanga [OPTIONS] COMMAND [ARGS]...\n\n", speed: 26, variance: 7 },
  { text: "Commands:\n", speed: 28, variance: 8 },
  { text: "  search   Terminal-based search workflow\n", speed: 24, variance: 6 },
  { text: "  install  Process and package content into CBZ\n", speed: 24, variance: 6 },
  { text: "  config   Update local configuration\n", speed: 24, variance: 6 },
  { pause: 1100 },
  { clear: true, pause: 180 },
  { text: "$ kizamumanga config paths --cbz_path \"./output\"\n", speed: 48, variance: 14 },
  { text: "Output folder updated: ./output\n", speed: 30, variance: 8 },
  { pause: 420 },
  { text: "\n$ kizamumanga config output --color false --cropping_mode true\n", speed: 48, variance: 14 },
  { text: "Grayscale export enabled; automatic margin cropping enabled\n", speed: 30, variance: 8 },
  { pause: 1100 },
  { clear: true, pause: 180 },
  { text: "$ kizamumanga search \"sample-title\"\n", speed: 52, variance: 14 },
  { pause: 520 },
  { text: "\nFound matching entries\n", speed: 30, variance: 8 },
  { text: "> Select item from terminal workflow\n", speed: 32, variance: 10 },
  { pause: 900 },
  { clear: true, pause: 180 },
  { text: "$ kizamumanga install \"sample-title\" 10-15\n", speed: 52, variance: 14 },
  { pause: 640 },
  { text: "\nRunning async processing pipeline...\n", speed: 30, variance: 8 },
  { text: "[", speed: 18, variance: 4 },
  { text: "██████████████████", speed: 13, variance: 3 },
  { text: "] 100%\n", speed: 22, variance: 5 },
  { pause: 420 },
  { text: "\nApplying image conversion pipeline...\n", speed: 31, variance: 8 },
  { text: "Packaging processed images into CBZ files...\n", speed: 33, variance: 9 },
  { pause: 560 },
  { text: "\nDone: CBZ files saved in ./output", speed: 34, variance: 10 },
];

export const REMOTE_LOG_TERMINAL_SCRIPT = [
  { text: "$ javac -d bin src/*.java\n", speed: 52, variance: 14 },
  { pause: 520 },
  { text: "Compiled: LogServer, ClientHandler, LogClient\n", speed: 30, variance: 8 },
  { pause: 900 },
  { clear: true, pause: 180 },
  { text: "$ java -cp bin LogServer\n\n", speed: 50, variance: 12 },
  { pause: 360 },
  { text: "Remote Log Server started on port 5000\n", speed: 28, variance: 8 },
  { text: "Waiting for clients...\n\n", speed: 28, variance: 8 },
  { pause: 1100 },
  { clear: true, pause: 180 },
  { text: "$ java -cp bin LogClient\n\n", speed: 50, variance: 12 },
  { pause: 360 },
  { text: "Connecting to localhost:5000...\n", speed: 30, variance: 8 },
  { text: "Server -> Client: ENTER_NAME\n", speed: 30, variance: 9 },
  { text: "Client name: App1\n", speed: 32, variance: 10 },
  { text: "Server -> Client: WELCOME App1\n", speed: 30, variance: 9 },
  { pause: 1100 },
  { clear: true, pause: 180 },
  { text: "# Server terminal\n", speed: 32, variance: 10 },
  { text: "New client connected: /127.0.0.1\n", speed: 32, variance: 10 },
  { text: "ClientHandler thread started for App1\n", speed: 30, variance: 9 },
  { pause: 420 },
  { text: "Client -> Server: INFO Server started\n", speed: 32, variance: 10 },
  { text: "Valid level: INFO\n", speed: 30, variance: 9 },
  { text: "Formatting log entry...\n", speed: 30, variance: 9 },
  { text: "[2026-04-01 14:30:25] (App1) INFO Server started\n\n", speed: 28, variance: 8 },
  { pause: 420 },
  { text: "synchronized(FILE_LOCK)\n", speed: 32, variance: 10 },
  { text: "Writing to logs.txt...\n", speed: 30, variance: 9 },
  { text: "Server -> Client: LOG_RECEIVED\n\n", speed: 30, variance: 9 },
  { pause: 1100 },
  { clear: true, pause: 180 },
  { text: "# Multiple log levels\n", speed: 32, variance: 10 },
  { text: "Client -> Server: WARN High memory usage detected\n", speed: 30, variance: 9 },
  { text: "Server -> Client: LOG_RECEIVED\n\n", speed: 30, variance: 9 },
  { pause: 420 },
  { text: "Client -> Server: ERROR Connection failed\n", speed: 30, variance: 9 },
  { text: "Server -> Client: LOG_RECEIVED\n\n", speed: 30, variance: 9 },
  { pause: 900 },
  { clear: true, pause: 180 },
  { text: "# Disconnect protocol\n", speed: 32, variance: 10 },
  { text: "Client -> Server: SALIR\n", speed: 32, variance: 10 },
  { text: "Server -> Client: GOODBYE\n", speed: 32, variance: 10 },
  { text: "Client disconnected: App1", speed: 32, variance: 10 },
];
